# Generated by Django 5.0 on 2024-01-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_customuser_google_calendar_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(max_length=255),
        ),
    ]
